name: Haskell Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Haskell
        uses: sgillespie/actions/haskell@latest
        id: setup-haskell

      - name: Print PKG_CONFIG_PATH
        run: |
          echo "${PKG_CONFIG_PATH}"
          export PKG_CONFIG_PATH
          echo "$ pkg-config --modversion icu-i18n"
          pkg-config --modversion icu-i18n
          echo "$ pkg-config --libs --static icu-i18n"
          pkg-config --libs --static icu-i18n
